/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:05e74d16-eb0f-42da-8ae3-18e24386894a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_EpnRlUNBe",
    "aws_user_pools_web_client_id": "25eulrabo38ta954clqned59qj",
    "oauth": {},
    "aws_content_delivery_bucket": "client-20201011113252-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://client-20201011113252-hostingbucket-dev.s3-website-us-east-1.amazonaws.com",
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "student_subjects-dev",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "subjectApi",
            "endpoint": "https://1wdtm33xlg.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
